[project]
name = "dotman"
version = "0.7.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.13"
authors = [
    { name = "Aditya Pratap Singh Rathore", email = "247943295+aditya-jodha@users.noreply.github.com" }
]
dependencies = [
    "dulwich>=1.2.12",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "typer>=0.26.4",
]

[project.scripts]
dotman = "dotman.__cli__:main"

[tool.typer]
main = "dotman.__cli__:main"

[tool.uv]
required-version = ">=0.12.5"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.1",
    "pyright>=1.1.410",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.16",
    "ty>=0.0.54",
]

# --- Linting & Formatting (Ruff) ---

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "ARG", "B", "BLE", "C4", "DTZ", "E", "F", "FA", "FURB", "I", 
    "N", "NPY", "PD", "PERF", "PLC", "PLE", "PTH", "RET", "RUF", 
    "S", "SIM", "TC", "TID", "TRY", "UP", "W", "YTT"
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.pycodestyle]
# Avoids triggering E501 on task comments (like TODO, FIXME)
ignore-overlong-task-comments = true

# --- Testing & Coverage ---

[tool.coverage.run]
omit = [
    "src/dotman/errors/*",
    "tests/*",
    # TODO: Re-enable CLI coverage once dedicated CLI integration tests are added.
    "src/dotman/cli/app/*",
    "src/dotman/cli/profile/*",
    "src/dotman/cli/config/*",
]

[tool.coverage.report]
exclude_also = [
    'if __name__ == "__main__":',
]