name: Markdown Lint

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.mjs"
      - ".markdownlint.json"
      - ".github/workflows/markdownlint.yml"

  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.mjs"
      - ".markdownlint.json"
      - ".github/workflows/markdownlint.yml"

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "22"

      - name: Run Markdownlint
        run: npx --yes markdownlint-cli2 "**/*.md" "!**/.venv/**" "!**/node_modules/**" "!**/.git/**" "!**/dist/**" "!**/build/**"